[build]
base = ""
publish = "dist/sweet-home"
command = "npm run build"

[dev]
functionsPort = 1234
targetPort = 4200
port = 4242

#[functions."backup"]
#    schedule = "@weekly"

#[[headers]]
#for = "/*"
#[headers.values]
#Access-Control-Allow-Origin = "https://my-sweet-home.netlify.app/"
#Access-Control-Allow-Methods = "GET,PUT,POST,DELETE,OPTIONS"
#Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, cache-control, pragma, expires"
#Access-Control-Allow-Credentials = "true"

#[[redirects]]
#from = "/*"
#to = "/index.html"
#status = 200

[[redirects]]
from = "/sonos-auth"
to = "https://api.sonos.com/login/v3/oauth/access"
status = 302
force = true

[[redirects]]
from = "/sonos-api/*"
to = "https://api.ws.sonos.com/control/api/v1/:splat"
status = 302
force = true
