[build]
base = ""
publish = "dist/sweet-home"
command = "npm run build"

[dev]
functionsPort = 1234
targetPort = 4200
port = 4242

#[functions."backup"]
#    schedule = "@weekly"

#[[redirects]]
#from = "/*"
#to = "/index.html"
#status = 200

[[redirects]]
from = "/sonos-auth"
to = "https://api.sonos.com/login/v3/oauth/access"
status = 200
force = true

[[redirects]]
from = "/sonos-api/*"
to = "https://api.ws.sonos.com/control/api/v1/:splat"
status = 200
force = true
